sudo: required

language: node_js
node_js:
  - "node"

services:
  - mongodb
  - docker

cache:
  directories:
    - "node_modules"

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - docker-compose --version

install:
  - npm install

script:
  - npm start &
  - npm test
  - npm stop

  # kill mongod process to use one from docker container
  - sudo killall mongod

  - docker-compose pull
  - docker-compose build
  - docker images --all

  - docker-compose up &
  - npm test
  - docker-compose stop
